export const SEARCH_USER_BY_NAME = 'SEARCH_USER_BY_NAME';
export const SELECT_REPO = 'SELECT_REPO';

export const FETCH_USER_INFO_PENDING = 'FETCH_USER_INFO_PENDING';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

export const FETCH_REPOS_PENDING = 'FETCH_REPOS_PENDING';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';

export const FETCH_REPO_INFO_PENDING = 'FETCH_REPO_INFO_PENDING';
export const FETCH_REPO_INFO_SUCCESS = 'FETCH_REPO_INFO_SUCCESS';
export const FETCH_REPO_INFO_FAILURE = 'FETCH_REPO_INFO_FAILURE';